spring.application.name=CrudSpringBootDemo

spring.datasource.url = jdbc:mysql://localhost:3306/student_crud_db
spring.datasource.username = root
spring.datasource.password = 5uh917@Mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
